/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cr95hf */

#ifndef _Included_Cr95hf
#define _Included_Cr95hf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cr95hf
 * Method:    getUID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Cr95hf_getUID
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
